### ISSUE TITLE
flexible compilaton on older systems

### ISSUE THREAD

**Issue by mckaygerhard** [willbprog127/spiritvnc-fltk-no-libssh2#3]
curently it uses FLTK but forces too modern compiler ( C++11 )

for the love of gd, be inclusive and provide me option near in future! please

and hello men ! how are you! happy new year .. i send you a mail last week! mckaygerhard!

**Comment by willbprog127** [comment]
Thanks for the issue!  (BTW, I replied to your e-mail)

Requiring C++11 instead of older compilers was a tough decision, but since I did not get any feedback at the time, I went ahead with it.  I actually like to keep things as backward compatible as possible, so the change to C++11 was a little worrisome for me.

I'm not sure I can go back to an older C++ standard at this point.  I _will_ look into it but it would require a lot of workarounds for the 'luxury' features C++11 offers.

Thanks again :+1:

**Comment by mckaygerhard** [comment]
umm well gcc 4.7 can do that.. i will let open this issue until next week and then close if i cannot convert myselft to C++ older (mostly as i know its only initializer adn some template firms, let me xperience that and later post feedback)

**Comment by willbprog127** [comment]
Closing after waiting a while for feedback.  If you need this reopened, please let me know. :+1: :smile:

**Comment by mckaygerhard** [comment]
mail send to you @willbprog127
